### PR TITLE
Migrating chain-mon from optimism

### PR DESCRIPTION
**Pull request by raffaele-oplabs**
**Description**

Migrating chain-mon from optimism

**Tests**

Please describe any tests you've added. If you've added no tests, or left important behavior untested, please explain why not.

**Additional context**

Add any other context about the problem you're solving.

**Metadata**

- Fixes #[Link to Issue]

### CODE REVIEW

**Comment by tynes** [comment]
Just wondering if there are any updates on this getting merged

**Review by Ethnical — APPROVED** [review]
Sgtm! I will wait @raffaele-oplabs to merge it when is back tomorrow @tynes

**Comment by tynes** [comment]
Following up here, just wondering the status of this

**Comment by protolambda** [comment]
What is the status here? I am also really looking forward to this migration out of the mono-repo.

**Comment by tynes** [comment]
Following up on this as there are some nice CI improvements to speed things up in the protocol monorepo once this is merged and we can remove it from the protocol monorepo

**Comment by raffaele-oplabs** [comment]
Going to close this PR as we are not going to merge chain-mon in monitorism.

**Pull request closed without merging**
