### PR TITLE
Add `.coderabbit.yaml` to reduce noisiness of the coderabbit plugins. 

### PR DESCRIPTION
**Pull request by Ethnical**
**Description**

**Tests**

**Additional context**

**Metadata**

### CODE REVIEW

**Comment by Ethnical** [comment]
@coderabbitai configuration

**Review by raffaele-oplabs — APPROVED** [review]

**Comment by Ethnical** [comment]
@coderabbitai configuration

**Comment by Ethnical** [comment]
@coderabbitai summary

**Comment by Ethnical** [comment]
@coderabbitai summary

**Comment by Ethnical** [comment]
@coderabbitai

**Pull request merged**
